# Generated by Django 3.2.13 on 2022-05-11 13:45

from django.db import migrations, models
import records.settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=records.settings.get_recordings_storage, upload_to='')),
            ],
        ),
    ]
