# Generated by Django 3.2.13 on 2022-05-11 13:49

from django.db import migrations, models
import records.settings


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='file',
            field=models.FileField(max_length=1000, storage=records.settings.get_recordings_storage, upload_to=''),
        ),
    ]
